# Generated by Django 3.2.4 on 2021-06-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('man', 'man'), ('wonam', 'wonam'), ('kids', 'kids')], max_length=20),
        ),
    ]
